### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by wvbigdave** [CraftoryStudios/Craftory-External#9]
This occurs now at every boot. I have deleted the plugin and its config files and tried loading again to no avail.  

> 10:40:56 WARN]: [Craftory] ItemFrame error caught.
[10:40:56 WARN]: java.lang.NullPointerException
[10:40:56 WARN]:        at tech.brettsaunders.craftory.tech.power.core.block.machine.magnetiser.MagnetisingTable.spawnFrame(MagnetisingTable.java:119)
[10:40:56 WARN]:        at tech.brettsaunders.craftory.tech.power.core.block.machine.magnetiser.MagnetisingTable.afterLoadUpdate(MagnetisingTable.java:87)
[10:40:56 WARN]:        at tech.brettsaunders.craftory.api.blocks.CustomBlockFactory.createLoad(CustomBlockFactory.java:98)
[10:40:56 WARN]:        at tech.brettsaunders.craftory.api.blocks.CustomBlockStorage.loadSavedRegion(CustomBlockStorage.java:138)
[10:40:56 WARN]:        at tech.brettsaunders.craftory.api.blocks.CustomBlockStorage.loadAllSavedRegions(CustomBlockStorage.java:95)
[10:40:56 WARN]:        at tech.brettsaunders.craftory.api.blocks.CustomBlockManagerEvents.onWorldInit(CustomBlockManagerEvents.java:94)
[10:40:56 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor55.execute(Unknown Source)
[10:40:56 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[10:40:56 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[10:40:56 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:40:56 WARN]:        at tech.brettsaunders.craftory.api.sentry.LoggedPluginManager$1.callEvent(LoggedPluginManager.java:78)
[10:40:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[10:40:56 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:439)
[10:40:56 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[10:40:56 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[10:40:56 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[10:40:56 WARN]:        at java.lang.Thread.run(Thread.java:748)
[10:40:56 ERROR]: null
java.lang.NullPointerException: null
        at tech.brettsaunders.craftory.tech.power.core.block.machine.magnetiser.MagnetisingTable.spawnFrame(MagnetisingTable.java:119) ~[?:?]
        at tech.brettsaunders.craftory.tech.power.core.block.machine.magnetiser.MagnetisingTable.afterLoadUpdate(MagnetisingTable.java:87) ~[?:?]
        at tech.brettsaunders.craftory.api.blocks.CustomBlockFactory.createLoad(CustomBlockFactory.java:98) ~[?:?]
        at tech.brettsaunders.craftory.api.blocks.CustomBlockStorage.loadSavedRegion(CustomBlockStorage.java:138) ~[?:?]
        at tech.brettsaunders.craftory.api.blocks.CustomBlockStorage.loadAllSavedRegions(CustomBlockStorage.java:95) ~[?:?]
        at tech.brettsaunders.craftory.api.blocks.CustomBlockManagerEvents.onWorldInit(CustomBlockManagerEvents.java:94) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor55.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-206]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-206]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-206]
        at tech.brettsaunders.craftory.api.sentry.LoggedPluginManager$1.callEvent(LoggedPluginManager.java:78) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:439) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-206]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by wvbigdave** [comment]
Oops, sorry forgot to let you know versions:

Paper build 206
Craftory 0.2.6

**Comment by MMJ744** [comment]
Thanks for reporting the bug. It will be fixed in the next release.


Discord Server: https://discord.gg/VVNvnyE
